/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.sso.iam.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.security.sso.iam.model.Token;
import com.liferay.portal.security.sso.iam.model.TokenModel;
import com.liferay.portal.security.sso.iam.model.TokenSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Token service. Represents a row in the &quot;IAM_Token&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TokenModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TokenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenImpl
 * @see Token
 * @see TokenModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TokenModelImpl extends BaseModelImpl<Token> implements TokenModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a token model instance should use the {@link Token} interface instead.
	 */
	public static final String TABLE_NAME = "IAM_Token";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "id_", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table IAM_Token (uuid_ VARCHAR(75) null,id_ LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table IAM_Token";
	public static final String ORDER_BY_JPQL = " ORDER BY token.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY IAM_Token.id_ ASC";
	public static final String DATA_SOURCE = "fakeDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.security.sso.iam.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.security.sso.iam.model.Token"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.security.sso.iam.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.security.sso.iam.model.Token"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.security.sso.iam.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.security.sso.iam.model.Token"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Token toModel(TokenSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Token model = new TokenImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Token> toModels(TokenSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Token> models = new ArrayList<Token>(soapModels.length);

		for (TokenSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.security.sso.iam.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.security.sso.iam.model.Token"));

	public TokenModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Token.class;
	}

	@Override
	public String getModelClassName() {
		return Token.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("id", getId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Token.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Token toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Token)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TokenImpl tokenImpl = new TokenImpl();

		tokenImpl.setUuid(getUuid());
		tokenImpl.setId(getId());

		tokenImpl.resetOriginalValues();

		return tokenImpl;
	}

	@Override
	public int compareTo(Token token) {
		long primaryKey = token.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Token)) {
			return false;
		}

		Token token = (Token)obj;

		long primaryKey = token.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TokenModelImpl tokenModelImpl = this;

		tokenModelImpl._originalUuid = tokenModelImpl._uuid;

		tokenModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Token> toCacheModel() {
		TokenCacheModel tokenCacheModel = new TokenCacheModel();

		tokenCacheModel.uuid = getUuid();

		String uuid = tokenCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tokenCacheModel.uuid = null;
		}

		tokenCacheModel.id = getId();

		return tokenCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.security.sso.iam.model.Token");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Token.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Token.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _id;
	private long _columnBitmask;
	private Token _escapedModel;
}